#!/bin/zsh
# vim: filetype=sh

alias \
  L="gls -AFNhl --color=auto --group-directories-first" \
  act="source .venv/bin/activate" \
  cfg='cd $HOME/.config' \
  cfk='cd $HOME/.config/kitty' \
  cfn='cd $HOME/.config/nvim' \
  cft='cd $HOME/.config/tmux' \
  cfz='cd $ZDOTDIR' \
  clear="z4h-clear-screen-soft-bottom" \
  cls="z4h-clear-screen-soft-bottom" \
  cp="cp -iv" \
  d="docker" \
  dc="docker compose" \
  de="deactivate" \
  diff="diff --color=auto" \
  gc="git commit --allow-empty -m" \
  ga="git add -A" \
  gac="git add -A && git commit --allow-empty -m" \
  grep="grep --color=auto" \
  gs="git status" \
  gtsc='git commit -m ''"updated $(date)"' \
  h="head" \
  k="kubectl" \
  l="gls -1N --color=auto --group-directories-first" \
  ll="gls -AFNhl --color=auto --group-directories-first" \
  ls="gls -N --color=auto --group-directories-first" \
  mkd="mkdir -pv" \
  mv="mv -iv" \
  p3="python3" \
  rm="rm -v" \
  sdn="sudo shutdown -h now" \
  so='source $ZDOTDIR/.zshrc' \
  t="tail" \
  tw="timew" \
  v="nvim" \
  vfa='$EDITOR $HOME/.config/aliasrc' \
  vfg='$EDITOR $HOME/.config' \
  vfk='$EDITOR $HOME/.config/kitty/kitty.conf' \
  vfn='$EDITOR $HOME/.config/nvim' \
  vft='$EDITOR $HOME/.config/tmux/tmux.conf' \
  vfz='$EDITOR $ZDOTDIR/.zshrc'
