git:
  commit:
    autoWrapCommitMessage: true
    autoWrapWidth: 80
  pagers:
    - pager: delta --dark --paging=never --tabs=2
      colorArg: always
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#ff966c"
      - "bold"
    inactiveBorderColor:
      - "#589ed7"
    searchingActiveBorderColor:
      - "#ff966c"
      - "bold"
    optionsTextColor:
      - "#82aaff"
    selectedLineBgColor:
      - "#2d3f76"
    cherryPickedCommitFgColor:
      - "#82aaff"
    cherryPickedCommitBgColor:
      - "#c099ff"
    markedBaseCommitFgColor:
      - "#82aaff"
    markedBaseCommitBgColor:
      - "#ffc777"
    unstagedChangesColor:
      - "#c53b53"
    defaultFgColor:
      - "#c8d3f5"
  tabWidth: 2
  mouseEvents: true
  sidePanelWidth: 0.3
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 10
customCommands:
  - key: "E"
    command: 'git commit --allow-empty -m "{{ .Form.Summary }}"'
    context: "global"
    description: "Create an empty commit with a message"
    prompts:
      - type: "input"
        title: "Commit summary"
        key: "Summary"
quitOnTopLevelReturn: true
notARepository: skip
promptToReturnFromSubprocess: false
