#!/usr/bin/env sh
gh issue list -L 5 --state open --json number,title,updatedAt |
  jq -r '.[] | "\u001b[32m#\(.number | rpad(6)) \u001b[0m\(.title | ascii_rpad(40)) \u001b[38;2;84;92;126m\(.updatedAt | time_delta | ascii_lpad(8))"'
