#!/usr/bin/env sh
gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" '/notifications?per_page=5' |
  jq -r '.[] | "\u001b[32m\(read_status | rpad(2)) \u001b[35m\(.repository.name | rpad(16)) \u001b[0m\(.subject.title | rpad(32)) \u001b[38;2;84;92;126m\(notification_type | ascii_lpad(4))"'
