return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "basedpyright",
      "bash-language-server",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "gofumpt",
      "goimports",
      "golines",
      "gopls",
      "hadolint",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "prettier",
      "prisma-language-server",
      "revive",
      "ruff",
      "shfmt",
      "sqlfluff",
      "staticcheck",
      "stylua",
      "tailwindcss-language-server",
      "templ",
      "terraform-ls",
      "tflint",
      "tree-sitter-cli",
      "vtsls",
      "yaml-language-server",
    },
    ui = {
      icons = {
        package_installed = "✓",
        package_pending = "⋯",
        package_uninstalled = "✗",
      },
    },
  },
}
