return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "basedpyright",
      "bash-language-server",
      "codelldb",
      "delve",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "elixir-ls",
      "erb-formatter",
      "erb-lint",
      "eslint-lsp",
      "gofumpt",
      "goimports",
      "golines",
      "gomodifytags",
      "gopls",
      "hadolint",
      "helm-ls",
      "impl",
      "java-debug-adapter",
      "java-test",
      "jdtls",
      "js-debug-adapter",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "prettier",
      "prisma-language-server",
      "revive",
      "rubocop",
      "ruby-lsp",
      "ruff",
      "rust-analyzer",
      "shellcheck",
      "shfmt",
      "sqlfluff",
      "staticcheck",
      "stylua",
      "tailwindcss-language-server",
      "taplo",
      "templ",
      "terraform-ls",
      "tflint",
      "tree-sitter-cli",
      "vtsls",
      "yaml-language-server",
    },
    ui = {
      icons = {
        package_installed = "✓",
        package_pending = "⋯",
        package_uninstalled = "✗",
      },
    },
  },
}
